updated- executable

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -6,5 +6,11 @@ if [ $# -lt 4 ]
 then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
+  # Check the exit status of the scp command
+    if [ "$?" -eq 0 ]; then
+        echo "File transferred successfully."
+    else
+        echo "Error transferring the file."
+    fi
 fi
